<?php include "db.php";

///////////////////////////////////////////////////////////////////////////////////////////
// Web inteface for ReMOAT-Reannotation and Mapping of Oligonucleotide Array Technologies//
// Shamith Samarajiwa 2009							         //
// PHP interface to ReMOAT mysql database populated with data generated by		 //
// Nuno Barbosa-Morais et al.								 //
// University of Cambridge 2009							         //
///////////////////////////////////////////////////////////////////////////////////////////

$search = $_POST["search"];
$species= $_POST["species"];
$ids= $_POST["ids"];
$outidtype= $_POST["outidtype"];
$platform= $_POST["platform"];

if (!isset($_POST["Submit"])) { // if page is not submitted to itself echo the form

?>

<?PHP include "header.php" ?>
<div id="preamble">
<h3><span><center><b>Gene ID Converter</b></center></span></h3>
<h3><span></span></h3>

<p class="p1"><span>
<h3><span></span></h3><br />
<h4>Paste gene ID's in box</h4>

			<center>
<form method="post" action="<?php echo $PHP_SELF;?>">


<textarea rows="30" cols="30" name="search" wrap="physical">Gene IDs</textarea><br />
<br><br>


<b>Select input ID type:</b><br>
<select name="ids">
<option value="1">Illumina</option>
<option value="2">Ensembl</option>
<option value="3">Entrez</option>

</select>
<br><br>
<br><br>

<table>
<th>Speices:</th>
<tr><td>Human:</td><td><input type="radio" value="1" name="species"></td></tr>
<tr><td>Mouse:</td><td><input type="radio" value="2" name="species"></td></tr>
<tr><td>Rat  :</td><td><input type="radio" value="3" name="species"></td></tr>
</table>
<br><br>

<b> Select Platform:</b><br>
<select name="platform">
<option value="1">Illumina_Human_WG-6_V1_hg18</option>
<option value="2">Illumina_Human_WG-6_V2_hg18</option>
<option value="3">Illumina_Human_WG-6_V3_hg18</option>
<option value="5">Illumina_Mouse_WG-6_V1.1</option>
<option value="6">Illumina_Mouse_WG-6_V2</option>
<option value="7">Illumina_Rat_Ref-12_V1</option>
</select>

<br><br>
<br><br>

<table>
<th>Select multiple output ID types:</th>
<tr><td>Illumina:</td><td><input type="checkbox"  name="outidtype[]" value="illumina_proid"></td></tr>
<tr><td>Ensembl:</td><td><input type="checkbox" name="outidtype[]" value="ensembl_id"></td></tr>
<tr><td>Entrez:</td><td><input type="checkbox"  name="outidtype[]" value="entrez_id"></td></tr><br>
<tr><td>Gene Symbol:</td><td><input type="checkbox" name="outidtype[]" value="gene_symbol"></td></tr>
<tr><td>Unigene:</td><td><input type="checkbox" name="outidtype[]" value="unigene_id" ></td></tr>
<tr><td>Lumi:</td><td><input type="checkbox"  name="outidtype[]" value="lumi_id"></td></tr>
<tr><td>Cytoband:</td><td><input type="checkbox"  name="outidtype[]" value="cyto_band"></td></tr>
</table>


</center>
<br><br>
<p><span><center>
<input type="submit" value="Submit" name="Submit">
<input type="button" value="Reset" onclick="this.form.elements['search'].value=''">
</center></span></p></span></p></div>
</div>

<div id="supportingText">
<div id="explanation">
<h3><span></span></h3>
<p class="p1"><span></span></p>

<p class="p2"><span></span></p>
</div>

<div id="participation">
<h3><span>

</span></h3></p>

<p class="p2"><span></span></p>

<p class="p3"><span></span></p>

</div>

<div id="benefits">
<h3><span></span></h3>

<p class="p1"><span></span></p>
</div>

<div id="requirements">

<h3><span></span></h3>

<p class="p1"><span></span></p>

<p class="p2"><span></span></p>
<p class="p3"><span></span></p>
<p class="p4"><span></span></p>

<p class="p5"><span></span>&nbsp;</p>
</div>

<?PHP include "footer.php"?>
</div>
<?PHP include "menu.php"; ?>
</body>
</html>

<?
} 
else 
{
	if 	(count($outidtype)>0){ #multi tickbox selection via array
		for ($zz=0; $zz<count($outidtype); $zz++){
		

		
		$find=$find.",".$outidtype[$zz]; #comma delimited list for selection from db
		
		$findit=substr($find,1); #get rid of first comma
		   		
		$findit=trim($findit);

		
		}
		
		
		
		}
	$search=trim($search);
	echo "<html><head></head><body bgcolor=#00CCFF><br><br><br>";
	$pieces = explode("\n", $search);
	

		
	
	//Can Only Search 50000 Genes
	if (count($pieces) > 50000)
	{
		$pieces =array_slice($pieces,0,50000);
		print "<p> <center>You Searched For More Than 50000 Genes. Only The First 50000 Values Were Considered </center></p>";
	}





	// TABLE form includes optional HTML arguments passed into function
        //Random Number Representing User
        $rand = rand(0, 25000);
	$myFile = "tmp/" .  $rand  . ".txt";
        $fh = fopen($myFile, 'w') or die("can't open file");

	
		


	$results = 0;
	#echo count($pieces);
	foreach ($pieces as $j)
	{
		
		$j=trim($j);
		
 		if ( $ids==1 ){ #$ids selects the id type submitted
			$pattern='/^(ILMN_)/'; #check for correct id type using regex
			#$pattern2='/^(ID_)/';
			if (preg_match($pattern, $j)){
			$query = "SELECT distinct platform_id, $findit, description FROM probeinfo WHERE (illumina_proid = '$j' and species_id='$species') and platform_id='$platform' order by illumina_proid";
			}
			else
			{
			echo "<center>";
			echo "ID type incorrect";
			echo "</center>";
			}
 		
		}
		else if ( $ids==2 ){
			$pattern='/^ENS.+[0-9]{11}$/';
			if (preg_match($pattern, $j))
			{
			$query = "SELECT distinct platform_id, $findit, description  FROM probeinfo WHERE (ensembl_id = '$j' and species_id='$species') and platform_id='$platform' order by ensembl_id";
			}
			else
			{
			echo "<center>";
			echo "ID type incorrect";
			echo "</center>";
			}
		}
		
		else if ( $ids==3 ){
			$pattern='/^[0-9]+$/';
			if (preg_match($pattern, $j))
			{
			$query = "SELECT distinct platform_id, $findit, description FROM probeinfo WHERE (entrez_id = '$j' and species_id='$species') and platform_id='$platform' order by entrez_id";
			}
			else
			{
			echo "<center>";
			echo "ID type incorrect";
			echo "</center>";
			}			

		}


		#echo $j;
		



		#echo "<p>$query</p>";
		$result = mysql_query ($query);
		
		//grab all the content
		while($row=mysql_fetch_array($result)) 
		
		
		
		
		
		
		
		
		
		{
			$left = 0;
			$right = 0;
			
			// the format is $variable = $row["nameofmysqlcolumn"]
			
			
			$illumina=$row["illumina_proid"];
			$platform=$row["platform_id"];
			$lumi=$row["lumi_id"];
			$symbol=$row["gene_symbol"];
			$synonym=$row["synonym"];
			$ensembl=$row["ensembl_id"];
			$unigene=$row["unigene_id"];
			$description=$row["description"];
			$entrez=$row["entrez_id"];
			$band=$row["cyto_band"];
			
			
			
			//Write File
            		$stringData = $row["illumina_proid"] . "\t" .$row["ensembl_id"]."\t" . $row["entrez_id"] . "\t" . $row["lumi_id"] . "\t" . $row["gene_symbol"] . "\t" . $row["synonym"] . "\t" .$row["cyto_band"]. "\t" .$row["unigene_id"]."\n";
             		fwrite($fh, $stringData);
			
			#Draw The Row
			if ($results == 0)
			{
				#Draw The Table Header If Results Exist
				print("<center><h2>ID Converter</center></h2>");
				echo "<center>";
				echo "<table border=2 >";
				echo "<tr><th>Platform ID</th><th>Illumina probe</th><th>Lumi id</th><th>Gene Symbol</th><th>Ensembl</th><th>Entrez</th><th>Unigene</th><th>Cyto Band</th><th>Description</th><th>iHOP</th><th>Wiki Genes</th></tr>";
				$results = 1;
				
				
			}	
			
			
			

			
			{ 
			
			if ($species==1){
			$speciestype="Homo_sapiens";
			}
			else if ($species==2){
			$speciestype="Mus_musculus";
			}
			else if ($species==3){
			$speciestype="Rattus_norvegicus";
			}
			
			#echo $species;
				
			echo "<tr><td><a>$platform</a></td><td><a>$illumina</a></td><td><a>$lumi</a></td><td><a href=http://www.genenames.org/data/hgnc_data.php?match=$symbol><center>$symbol</center></a></td><td><a href=http://www.ensembl.org/$speciestype/Gene/Summary?g=$ensembl>$ensembl</a></td><td><a href=http://view.ncbi.nlm.nih.gov/gene/$entrez><center>$entrez</center></a></td><td><a>$unigene</a></td><td><a>$band</a></td><td><a>$description</a></td><td><a href=http://www.ihop-net.org/UniPub/iHOP/in?dbrefs_1=NCBI_GENE__ID|$entrez>iHop</a></td><td><a href=http://www.wikigenes.org/e/gene/e/$entrez.html>wikigenes</a></td></tr>";

			}





		}
	}
	
	
	if ($results == 1)
	{
		
		fclose($fh);
		echo "</table>";
		echo "<br>";

	echo "NOTE: iHOP and Wikigenes links are active only for those records with Entrez Gene ID's";
	echo "<br><br><br>";

	//Echo download file
        echo "<a href='tmp/" . $rand . ".txt'>Click Here To Download Table As A Tab Delimited Text File</a>";
	echo "<br><br>";
	echo "<br><br>";
	echo 'Please <a href="search.php">click here</a> to search again';

		
	echo "<br>";

		
	}
	else
	{
		echo "<center>";
		echo "<br>";
		echo 'No Results Were Found. <br> Please check gene ID type and platform ID<br><br><br>Please <a href="search.php">click here</a> to search again';
		echo "</center>";
	}
	
}
?>
</body>
</html>
