<?php include "db.php";

///////////////////////////////////////////////////////////////////////////////////////////
# Web inteface for ReMOAT-Reannotation and Mapping of Oligonucleotide Array Technologies  #
# Shamith Samarajiwa 2009							          #
# PHP interface to remoat mysql database populated with data generated by		  #
# Nuno Barbosa-Morais 	et al.								  #
# University of cambridge								  #
///////////////////////////////////////////////////////////////////////////////////////////

// Probe sequence information page

$search = $_POST["search"];
$outidtype= $_POST["outidtype"];
$platform= $_POST["platform"];

if (!isset($_POST["Submit"])) { // if page is not submitted to itself echo the form

?>

<?PHP include "header.php" ?>
<div id="preamble">
<h3><span><center><b>Probe Information</b></center></span></h3>
<h3><span></span></h3>

<p class="p1"><span>
<h3><span></span></h3><br />
<h4>Paste Illumina ID's</h4>

<center>
<form method="post" action="<?php echo $PHP_SELF;?>">


<textarea rows="30" cols="30" name="search" wrap="physical">Illumina ID</textarea><br />




Platform:<br>
<select name="platform">
<option value="2">Illumina_Human_WG-6_V2_hg18</option>
<option value="3">Illumina_Human_WG-6_V3_hg18</option>
<option value="5">Illumina_Mouse_WG-6_V1.1</option>
<option value="6">Illumina_Mouse_WG-6_V2</option>
<option value="7">Illumina_Rat_Ref-12_V1</option>
</select>

<br><br>
<br>

<table>
<th>Select output ID type:</th><br />
<tr><td>Illumina ID:</td><td><input type="checkbox"  name="outidtype[]" value="illumina_proid"></td></tr>
<tr><td>Probe Sequence:</td><td><input type="checkbox" name="outidtype[]" value="pro_seq"></td></tr>
<tr><td>Probe Type:</td><td><input type="checkbox"  name="outidtype[]" value="probe_type"></td></tr>
<tr><td>Repeat Mask:</td><td><input type="checkbox" name="outidtype[]" value="repeat_mask"></td></tr>
<tr><td>CpG island:</td><td><input type="checkbox" name="outidtype[]" value="CpG_island" ></td></tr>
<tr><td>GC content:</td><td><input type="checkbox"  name="outidtype[]" value="gc_content"></td></tr>
<tr><td>SNP number:</td><td><input type="checkbox"  name="outidtype[]" value="snp_number"></td></tr>
<tr><td>Quality:</td><td><input type="checkbox"  name="outidtype[]" value="quality_score"></td></tr>
<tr><td>Comments:</td><td><input type="checkbox"  name="outidtype[]" value="quality_comments"></td></tr>
</table>

</center>
<br><br>
<p><span><center>
<input type="submit" value="Submit" name="Submit">
<input type="button" value="Reset" onclick="this.form.elements['search'].value=''">
</center></span></p></span></p></div>
</div>

<div id="supportingText">
<div id="explanation">
<h3><span></span></h3>
<p class="p1"><span></span></p>

<p class="p2"><span></span></p>
</div>

<div id="participation">
<h3><span>

</span></h3></p>

<p class="p2"><span></span></p>

<p class="p3"><span></span></p>

</div>

<div id="benefits">
<h3><span></span></h3>

<p class="p1"><span></span></p>
</div>

<div id="requirements">

<h3><span></span></h3>

<p class="p1"><span></span></p>

<p class="p2"><span></span></p>
<p class="p3"><span></span></p>
<p class="p4"><span></span></p>

<p class="p5"><span></span>&nbsp;</p>
</div>

<?PHP include "footer.php"?>
</div>
<?PHP include "menu.php"; ?>
</body>
</html>

<?
} 
else 

{
	##$table="s.";
	if 	(count($outidtype)>0){ #multi tickbox selection via array
		for ($zz=0; $zz<count($outidtype); $zz++){
		

		
		##$find=$find.",".$table.$outidtype[$zz]; #comma delimited list for selection from db
		$find=$find.",".$outidtype[$zz]; #comma delimited list for selection from db
		
		$findit=substr($find,1); #get rid of first comma
		   		
		$findit=trim($findit);

		
		}
		
		
		}
	echo "<html><head></head><body bgcolor=#00CCFF><br><br><br>";
	$pieces = explode("\n", $search);
	

		
	
	//Can Only Search 50000 Genes
	if (count($pieces) > 50000)
	{
		$pieces =array_slice($pieces,0,50000);
		print "<p> You Searched For More Than 50000 Genes. Only The First 50000 Values Were Considered </p>";
	}

	



	// TABLE form includes optional HTML arguments passed into function
        //Random Number Representing User
        $rand = rand(0, 25000);
	$myFile = "tmp/" .  $rand  . ".txt";
        $fh = fopen($myFile, 'w') or die("can't open file");


		


	$results = 0;
	
	foreach ($pieces as $j)
	{
		$j=trim($j);

 		

		
		 
		
		#$query = "SELECT $findit FROM sequence s inner join probeinfo p WHERE s.illumina_proid=p.illumina_proid and illumina_proid = '$j' and p.species_id='$species' and p.platform_id='$platform'";
		##$query = "SELECT $findit FROM sequence s inner join probeinfo p WHERE p.illumina_proid=s.illumina_proid and s.illumina_proid = '$j' and p.species_id='$species' and p.platform_id='$platform'";##need to check this query
		#$query = "SELECT $findit FROM sequence WHERE illumina_proid = '$j' and species_id='$species' and platform_id='$platform'";
		
		$pattern='/^(ILMN_)/';
		if (preg_match($pattern, $j)){
		
			$query = "SELECT $findit FROM sequence WHERE illumina_proid = '$j' and platform_id='$platform'";
		}
		else
			{
			echo "<center>";
			echo "ID type incorrect";
			echo "</center>";
		}
		
		$result = mysql_query ($query);
		
		//grab all the content
		while($row=mysql_fetch_array($result)) 
		{
			$left = 0;
			$right = 0;
			
			// the format is $variable = $row["nameofmysqlcolumn"]
			
			
			$illumina=$row["illumina_proid"];
			$probeseq=$row["pro_seq"];
			$probetype=$row["probe_type"];
			$repeat=$row["repeat_mask"];
			$cpg=$row["CpG_island"];
			$gc=$row["gc_content"];
			$snpnum=$row["snp_number"];
			$qscore=$row["quality_score"];
			$comments=$row["quality_comments"];
			
			
			//Write File
            		$stringData = $row["illumina_proid"] . "\t" .$row["pro_seq"]."\t" . $row["probe_type"] . "\t" . $row["repeat_mask"] . "\t" . $row["gene_symbol"] . "\t" . $row["CpG_island"] .
			"\t" .$row["gc_content"]. "\t" .$row["snp_number"]."\t".$row["quality_score"]. "\t" .$row["quality_comments"]. "\n";
             		fwrite($fh, $stringData);
			
			#Draw The Row
			if ($results == 0)
			{
				#Draw The Table Header If Results Exist
				print("<center><h2>Probe Reannotation</center></h2>");
				echo "<center>";
				echo "<table border=2 >";
				echo "<tr><th>Illumina probe</th><th>Probe Sequence</th><th>Probe Type</th><th>Repeats</th><th>CpG Islands</th><th>GC%</th><th>SNP's</th><th>quality score</th><th>quality comments</th></tr>";
				$results = 1;
			}
			

echo "<tr><td><a>$illumina</a></td><td><a>$probeseq</a></td><td><a>$probetype</a></td><td><a>$repeat</a></td><td><a>$cpg</a></td><td><a>$gc</a></td><td><a>$snpnum</a></td><td><a>$qscore</a></td><td><a>$comments</a></td></tr>";





		}


	}
	
	
	if ($results == 1)
	{
		
		fclose($fh);
		echo "</table>";
		echo "<br><br>";



	//Echo download file
	echo "<center>";
        echo "<a href='tmp/" . $rand . ".txt'>Click Here To Download Table as a Tab Delimitted Text File</a>";
	echo "<br><br>";
	echo "<BR<BR>";
	echo 'Please <a href="sequence.php">click here</a> to search again';
	echo "</center>";


		
		echo "<br>";

		
	}
	else
	{
		echo "<center>";
		echo 'No Results Were Found.<br><br>Please <a href="sequence.php">Click Here</a> To Search Again';
		echo "</center>";
	}
	
}
?>
</body>
</html>
